### ISSUE TITLE
cannot install this module

### ISSUE THREAD

**Issue by legleux** [rismoney/puppet-windowsnetwork#7]
the chocolatey module works fine though.

`puppet module install rismoney-windowsnetwork`
Notice: Preparing to install into /etc/puppet/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install 'rismoney-windowsnetwork' (latest)
  No releases are available from https://forgeapi.puppetlabs.com
    Does 'rismoney-windowsnetwork' have at least one published release?

**Comment by fraenki** [comment]
@rismoney: Could you please release a new version on Puppet Forge?

**Comment by rismoney** [comment]
Sure will do
